Seed/notes comments
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #10
Opened 2024-11-04 19:45 UTC by YOUNS28100

I created seeding about comments and rating in every movie. I needed to seed some users too to seed the rest properly. Also this PR contain the dev merge from last week because i created my branch before.

2024-11-05 08:20 UTC, Ludovicscelles approved these changes, later dismissed

2024-11-05 11:04 UTC, brewost submitted a review, later dismissed

2024-11-05 11:20 UTC, jujuck requested changes
Pourquoi ces fichiers, quel rapport avec le seed ?

2024-11-05 11:20 UTC, jujuck commented on api/src/resolvers/UserResolver.ts
Pourquoi ce fichier, quel rapport avec le seed ?

2024-11-05 11:20 UTC, jujuck commented on api/src/types/User.types.ts
Pourquoi ce fichier, quel rapport avec le seed ?

2024-11-05 11:20 UTC, jujuck commented on client/src/components/SignIn.tsx
Pourquoi ce fichier, quel rapport avec le seed ?

2024-11-05 11:20 UTC, jujuck commented on client/src/components/SignUp.tsx
Pourquoi ce fichier, quel rapport avec le seed ?

2024-11-05 11:20 UTC, jujuck commented on client/src/generated/graphql-types.ts
Pourquoi ce fichier, quel rapport avec le seed ?

2024-11-05 23:58 UTC, YOUNS28100 commented on api/src/data/create.ts
> +    await queryRunner.query("DELETE FROM sqlite_sequence");
refacto en une seule ligne

2024-11-05 23:59 UTC, YOUNS28100 commented on api/src/data/create.ts
> +): Promise<void> {
Erreur TS, j'ai du rajouté le typage du return

2024-11-05 23:59 UTC, YOUNS28100 commented on api/src/data/create.ts
> +): Promise<void> {
Erreur TS, j'ai du rajouté le typage du return

2024-11-06 00:02 UTC, YOUNS28100 commented
Les fichiers "en trop" viennent du merge de la branche dev suite aux récentes PR. Pour le reste, j'ai ajouté le seed de l'entité Avatar (relations avec mes users) que j'avais oublié de faire.

2024-11-06 07:29 UTC, brewost submitted a review, later dismissed

2024-11-06 07:38 UTC, Ludovicscelles submitted a review, later dismissed

2024-11-06 10:14 UTC, jujuck requested changes

2024-11-06 10:14 UTC, jujuck commented on api/src/data/create.ts
> +      .map((e) => path.posix.join(avatarPathFolder, e.name));
Reprendre le path

2024-11-06 10:28 UTC, brewost approved these changes

2024-11-06 10:29 UTC, Ludovicscelles approved these changes

2024-11-06 10:53 UTC, jujuck approved these changes

2024-11-06 10:53 UTC, merged