Ajout des fichiers seed, fetch et create pour reset et peupler la bdd avec l'api
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #2
Opened 2024-10-17 15:08 UTC by alexandreg67

Création du fichier seed.ts :
Ajout de la fonctionnalité de reset de la BDD.
Création du fichier fetch.ts :
Récupérer les données à partir de l'api
Création du fichier create.ts :
Lit les données récupérérées depuis les fichiers .json et les insère dans la bdd.

Un script reset-db permet d'automatiser le processus de réinitialisation et le peuplement de la bdd avec des données provenant de l'api TMDB.

Ajout des entités Typeorm pour gérer les nouvelles données.
Ajout des types pour gérer les données récupérées.

Envisager l'ajout de tests pour le fichier create.ts pour s'assurer que les insertions se passent bien.
( exemple : Overview peut-être vide donc on a mis une string vide )

2024-10-18 08:21 UTC, YOUNS28100 approved these changes, later dismissed

2024-10-18 08:21 UTC, Ludovicscelles submitted a review, later dismissed

2024-10-18 08:21 UTC, brewost submitted a review, later dismissed
good work

2024-10-18 09:44 UTC, jujuck requested changes

2024-10-18 09:44 UTC, jujuck commented on api/src/data/create.ts
> +    for (const filmData of films) {
Utilise une approche Promise.all qui sera plus efficace.
Cela va parallélisé les lancements de requete plutot que d'attendre le resultat de la requete pour avance dans ta boucle

const savedLangs = await Promise.all(
      lang.map(async (el) => {
        const lang = new Lang();
        lang.name = el;
        return lang.save();
      })
    );

2024-10-18 09:44 UTC, jujuck commented on api/src/entities/Film.ts
> +export class Film {
Passe en mode BaseEntity

2024-10-18 09:44 UTC, jujuck commented on api/src/data/create.ts
> +import { Repository } from "typeorm";
Pas besoin  sur tu passes tes entitées en mode BaseEntity

2024-10-18 09:44 UTC, jujuck commented on api/src/data/create.ts
> +    const filmRepo = AppDataSource.getRepository(FilmEntity);
Avec Base Entity, tu n'en auras plus besoin cf bac a sable

2024-10-18 09:44 UTC, jujuck commented on api/src/data/create.ts
> +    film.director = directors.join(", ");
directors si plusieurs ou alors directors[0]

2024-10-18 09:44 UTC, jujuck commented on api/src/data/fetch.ts
> +  await fetchAndSaveCredits();
En étape :
const savedFilms = await fetchAndSaveFilms()
const saveCredits = await fetchAndSaveFilms(savedFilms)
await write....savedFilms
await write ... savedCredits

2024-10-18 09:44 UTC, jujuck commented on api/src/db/data-source.ts
> +  entities: [Film, User, UserComments, UserFavorites, UserRating, Avatar],
Supprimer les entités inutiles

2024-10-18 09:44 UTC, jujuck commented on api/src/db/seed.ts
> +import { AppDataSource } from "./data-source";
Fusion avec le create

2024-10-19 10:01 UTC, alexandreg67 commented on api/src/data/create.ts
> +    for (const filmData of films) {
Mise en place de Promise.all 
```typescript
await Promise.all(
      films.map(async (filmData: Film) => {
        const filmCredits = credits.find(
          (credit: FilmCredits) => credit.filmId === filmData.id
        );
        if (filmCredits) {
          await insertFilm(filmData, filmCredits);
        }
      })
    );

2024-10-19 10:02 UTC, alexandreg67 commented on api/src/entities/Film.ts
> +export class Film {
Fait :
```typescript
@Entity()
export class Film extends BaseEntity {

2024-10-19 10:03 UTC, alexandreg67 commented on api/src/data/create.ts
> +import { Repository } from "typeorm";
J'ai supprimé l'import de Repository :
```typescript
import { CastMember, CrewMember, FilmCredits, Film } from "../types/film.types";
import { AppDataSource } from "../db/data-source";
import { Film as FilmEntity } from "../entities/Film";
import * as fs from "fs/promises";
import * as path from "path";

2024-10-19 10:04 UTC, alexandreg67 commented on api/src/data/create.ts
> +    const filmRepo = AppDataSource.getRepository(FilmEntity);
J'ai supprimé la const filmRepo

2024-10-19 10:05 UTC, alexandreg67 commented on api/src/data/create.ts
> +    film.director = directors.join(", ");
J'ai modifié pour n'ajouter que le premier réalisateur :
```typescrip
    const directors = filmCredits.crew
      .filter((crewMember: CrewMember) => crewMember.job === "Director")
      .map((director: CrewMember) => director.name);
    film.director = directors[0];

2024-10-19 10:07 UTC, alexandreg67 commented on api/src/data/fetch.ts
> +  await fetchAndSaveCredits();
Mise en place des constantes savedFilms et savedCredits :
```typescript
    // Récupérer les films
    const savedFilms = await fetchFilms();

    // Récupérer les crédits des films récupérés
    const savedCredits = await fetchCredits(savedFilms);

    // Écrire les films et les crédits dans les fichiers JSON
    await fs.writeFile(rawPathFilms, JSON.stringify(savedFilms, null, 2));
    await fs.writeFile(rawPathCredits, JSON.stringify(savedCredits, null, 2));

2024-10-19 10:07 UTC, alexandreg67 commented on api/src/db/data-source.ts
> +  entities: [Film, User, UserComments, UserFavorites, UserRating, Avatar],
Fait

2024-10-19 10:09 UTC, alexandreg67 commented on api/src/db/seed.ts
> +import { AppDataSource } from "./data-source";
J'ai fusionné le seed et le create pour ne conserver que le create.
J'ai modifié le script du package.json, il n'y a plus de seed :
```typescript
    "fetch": "ts-node src/data/fetch.ts",
    "create": "ts-node src/data/create.ts",
    "reset-db": "npm run fetch && npm run create"

2024-10-20 11:36 UTC, YOUNS28100 approved these changes

2024-10-20 17:26 UTC, Ludovicscelles approved these changes

2024-10-21 12:26 UTC, jujuck approved these changes

2024-10-21 12:26 UTC, merged