Page detail feature/comments
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #20
Opened 2024-11-07 18:18 UTC by brewost

Add in comments to the film details page - make the params dynamic.

2024-11-07 22:30 UTC, YOUNS28100 commented on client/src/components/FilmComments.tsx
> +  if (error) return <p>Error loading comments: {error.message}</p>;
In French please 😁

2024-11-07 22:31 UTC, YOUNS28100 commented on client/src/components/FilmComments.tsx
> +    return <p>No comments available for this film.</p>;
In French too please 😁

2024-11-07 22:36 UTC, YOUNS28100 requested changes
Need to switch some text in english to french please

2024-11-08 06:54 UTC, brewost commented on client/src/components/FilmComments.tsx
> +  if (error) return <p>Error loading comments: {error.message}</p>;
in french🤣

2024-11-08 06:54 UTC, brewost commented on client/src/components/FilmComments.tsx
> +    return <p>No comments available for this film.</p>;
in french - sorry!😂

2024-11-08 07:31 UTC, YOUNS28100 submitted a review, later dismissed

2024-11-08 08:07 UTC, alexandreg67 approved these changes, later dismissed

2024-11-08 08:07 UTC, Ludovicscelles submitted a review, later dismissed

2024-11-08 08:22 UTC, jujuck requested changes

2024-11-08 08:22 UTC, jujuck commented on api/src/resolvers/FilmResolver.ts
> +    return UserComment.find({
ON va le faire en 2 temps
const userComment = await ...
return userComment

2024-11-08 08:22 UTC, jujuck commented on client/src/components/FilmComments.tsx
> +
Réorganise

2024-11-08 08:22 UTC, jujuck commented on client/src/components/FilmComments.tsx
> +            key={index}
Pas d'index en key

2024-11-08 08:22 UTC, jujuck commented on client/src/pages/PageFilmDetail.tsx
> +  const filmId = id ? parseInt(id) : NaN;
Pas besoin de ternaire, parseInt de undefined renvoie NaN

2024-11-08 09:27 UTC, alexandreg67 approved these changes, later dismissed

2024-11-08 10:00 UTC, Ludovicscelles submitted a review, later dismissed

2024-11-08 10:16 UTC, jujuck submitted a review, later dismissed

2024-11-08 10:47 UTC, jujuck approved these changes

2024-11-08 10:47 UTC, merged