display of research result in DisplayFilms component
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #21
Opened 2024-11-07 20:10 UTC by Ludovicscelles

The goal of this feature is to display the search results within the DisplayFilm component.

2024-11-07 22:41 UTC, YOUNS28100 approved these changes, later dismissed

2024-11-08 08:04 UTC, alexandreg67 approved these changes, later dismissed

2024-11-08 08:11 UTC, jujuck requested changes

2024-11-08 08:11 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +            searchTerm
Pour simplifier, évite la cascade de ternaire.
une approche { searchBy === Criteria.Title && "Résultat...."}
{ searchBY === .... && }
Etc.
Sera plus lisisble

2024-11-08 08:55 UTC, brewost approved these changes, later dismissed

2024-11-08 08:58 UTC, alexandreg67 submitted a review, later dismissed

2024-11-08 09:48 UTC, jujuck approved these changes, later dismissed

2024-11-08 09:53 UTC, brewost approved these changes

2024-11-08 09:57 UTC, alexandreg67 approved these changes

2024-11-08 10:06 UTC, merged