Ajout du composant SearchBar avec requête GraphQL pour la recherche de films
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #3
Opened 2024-10-24 13:56 UTC by alexandreg67

Cette pull request ajoute un composant React SearchBar qui permet de rechercher des films à partir d'une requête GraphQL. La logique de requête est gérée via Apollo Client, GraphQL Codegen et le backend GraphQL pour récupérer une liste de films en fonction du titre saisi par l'utilisateur.

Changements apportés :
- Création du fichier `SearchBar.tsx` : logique de recherche.
- Configuration d'Apollo Client pour gérer la requête de films via SearchFilms généré par GraphQL Codegen.
- Ajout d'un SVG pour la loupe, rendu cliquable dans l'input.

Instructions pour tester :
1. Lancer l'application 
2. Saisir le nom d'un film dans la barre de recherche (ex : "Joker") et appuyer sur Enter.
3. Vérifier que la liste des films correspondant au titre s'affiche correctement dans la console.
4. Tester également la recherche en cliquant sur l'icône de la loupe.

2024-10-25 08:01 UTC, YOUNS28100 approved these changes, later dismissed

2024-10-25 08:43 UTC, brewost submitted a review, later dismissed
all good

2024-10-25 08:50 UTC, Ludovicscelles approved these changes, later dismissed

2024-10-25 09:21 UTC, jujuck requested changes
A finir avec les checkbox pour ne pas perdre le code de gestion de filtre
Uniquement 2 variables : filtre et type en enum
Tester la requete direct edans le resolver 
enum Criteria { "actor", "title", "directors"}

async function findFilms(filtre: string, type: Criteria): Promise<Film[]> {
  return await Film.find({
    where: [
      {[type]: Like(`%${filtre}%`) },
    ],
  });
}

2024-10-25 13:54 UTC, brewost submitted a review, later dismissed

2024-10-25 13:59 UTC, Ludovicscelles approved these changes, later dismissed

2024-10-25 14:40 UTC, jujuck requested changes
Reprendre la partie back pour la rendre dynamique en back,

2024-10-30 08:31 UTC, YOUNS28100 submitted a review, later dismissed

2024-10-30 08:31 UTC, Ludovicscelles submitted a review, later dismissed

2024-10-30 08:32 UTC, brewost submitted a review, later dismissed

2024-10-30 10:06 UTC, jujuck requested changes
Une question, quelle est l'étape d'après ? Une fois que la requête est reçue ?

2024-10-30 10:06 UTC, jujuck commented on client/src/components/SearchBar.tsx
> +  useEffect(() => {
Pourquoi mettre en place un useEffect qui ne fait rien

2024-10-30 10:06 UTC, jujuck commented on client/src/components/SearchBar.tsx
> +  const { data, loading, error } = useSearchFilmsQuery({
Je ne comprends pas, que fait tu de ta data une fois que tu l'as ?

2024-10-30 14:14 UTC, alexandreg67 commented on client/src/components/SearchBar.tsx
> +  const { data, loading, error } = useSearchFilmsQuery({
Comme on en a discuté, la homepage est maintenant chargée de faire la requête grâce aux params envoyé par la searchbar

2024-10-30 14:19 UTC, Ludovicscelles submitted a review, later dismissed

2024-10-30 15:27 UTC, brewost submitted a review, later dismissed

2024-10-30 15:28 UTC, Ludovicscelles approved these changes, later dismissed

2024-10-30 15:33 UTC, YOUNS28100 approved these changes, later dismissed

2024-10-30 16:04 UTC, jujuck requested changes

2024-10-30 16:04 UTC, jujuck commented on client/src/components/SearchBar.tsx
> +    if (searchTerm.trim()) {
Le if ne sert à rien car la fonction fonction trim renvoie la chaine de caractère
fait searchTerm.length > 0

2024-10-30 16:04 UTC, jujuck commented on client/src/components/SearchBar.tsx
> +  const [searchTerm, setSearchTerm] = useState("");
LE typage du state

2024-10-30 16:21 UTC, alexandreg67 commented on client/src/components/SearchBar.tsx
> +    if (searchTerm.trim()) {
Condition modifié par if (searchTerm.length > 0)

2024-10-30 16:21 UTC, alexandreg67 commented on client/src/components/SearchBar.tsx
> +  const [searchTerm, setSearchTerm] = useState("");
typage du useState en string

2024-10-30 16:32 UTC, Ludovicscelles approved these changes

2024-10-30 16:34 UTC, brewost approved these changes

2024-10-30 16:37 UTC, YOUNS28100 approved these changes

2024-10-31 07:51 UTC, jujuck approved these changes

2024-10-31 07:51 UTC, merged