Page detail feature/add film detail
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #5
Opened 2024-10-30 15:45 UTC by brewost

Add in detail page of film. ID currently hardcoded, it will be needed to be passed as params once possible. Comments and note feature to be added.

2024-10-30 15:50 UTC, alexandreg67 approved these changes, later dismissed

2024-10-30 15:50 UTC, Ludovicscelles submitted a review, later dismissed

2024-10-30 16:26 UTC, jujuck requested changes

2024-10-30 16:26 UTC, jujuck commented on client/src/pages/PageFilmDetail.tsx
> +      <div className="w-[70%] space-y-4 border border-bloodRed rounded p-6 mt-6 text-white text-left">
Une balise article ou section

2024-10-30 16:26 UTC, jujuck commented on client/src/pages/PageFilmDetail.tsx
> +        <div className="relative w-[30rem] h-[45rem] mt-5 mb-10">
une balise section

2024-10-30 16:26 UTC, jujuck commented on client/src/pages/PageFilmDetail.tsx
> +          <strong className="font-semibold">Overview:</strong> {film.overview}
Mets en place un padding ou margin pour simuler l'espace

2024-10-31 13:30 UTC, alexandreg67 submitted a review, later dismissed

2024-10-31 13:36 UTC, Ludovicscelles approved these changes, later dismissed

2024-10-31 13:48 UTC, jujuck requested changes

2024-10-31 13:48 UTC, jujuck commented on client/src/pages/PageFilmDetail.tsx
> +            <strong className="font-semibold mr-2">Synopsis:</strong>{" "}
Supprimer les espaces morts

2024-10-31 13:48 UTC, jujuck commented on client/src/main.tsx
> +        path: "/film/:id",
/films/:id

2024-10-31 14:01 UTC, alexandreg67 approved these changes

2024-10-31 14:33 UTC, YOUNS28100 approved these changes

2024-10-31 15:17 UTC, jujuck approved these changes

2024-10-31 15:17 UTC, merged