Feature/last films
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #8
Opened 2024-10-31 13:58 UTC by Ludovicscelles

Creation of the feature Lastfilms in the Hompage.

2024-10-31 14:04 UTC, brewost approved these changes, later dismissed

2024-10-31 14:06 UTC, YOUNS28100 approved these changes, later dismissed

2024-10-31 14:07 UTC, alexandreg67 approved these changes, later dismissed

2024-10-31 14:42 UTC, jujuck requested changes

2024-10-31 14:42 UTC, jujuck commented on client/src/components/LastFilms.tsx
> +            alt="Visuel montrant l'affiche du film {film.title}"
La balise alt ne doit pas être dynamqiue ? {...${film.title}}

2024-10-31 15:08 UTC, alexandreg67 approved these changes, later dismissed

2024-10-31 15:09 UTC, YOUNS28100 submitted a review, later dismissed

2024-10-31 15:33 UTC, jujuck submitted a review, later dismissed

2024-11-05 15:24 UTC, YOUNS28100 submitted a review, later dismissed

2024-11-05 15:24 UTC, brewost submitted a review, later dismissed

2024-11-05 15:28 UTC, alexandreg67 submitted a review, later dismissed

2024-11-05 16:04 UTC, jujuck approved these changes

2024-11-05 16:04 UTC, merged