Ajout du composant radiofilter pour séléctionner le type de recherche
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B pull request #9
Opened 2024-10-31 15:21 UTC by alexandreg67

Cette PR ajoute le composant RadioFilter et l’intègre dans le composant SearchBar pour améliorer l’expérience utilisateur lors de la recherche de films par titre, acteur ou réalisateur.

Composant RadioFilter :
Ce composant affiche trois options de filtre (titre, acteur, réalisateur) sous forme de boutons radio.
Ajout d'une icône de fermeture permettant à l'utilisateur de masquer le composant RadioFilter.

RadioFilter est visible lorsque l’utilisateur clique dans la SearchBar.
L’utilisateur peut fermer RadioFilter en cliquant sur la croix
Le critère de recherche sélectionné met à jour dynamiquement le placeholder dans SearchBar.

2024-11-04 20:33 UTC, brewost approved these changes, later dismissed

2024-11-04 21:27 UTC, Ludovicscelles approved these changes, later dismissed

2024-11-05 11:01 UTC, jujuck requested changes

2024-11-05 11:01 UTC, jujuck commented on client/src/pages/HomePage.tsx
> +      ) : searchTerm ? (
L'enchainement des ternaires nuit à la lisibilité du code...
Utilise plutôt du condition en &&
loading && <p>loading</p>
error && ....

2024-11-05 15:25 UTC, alexandreg67 commented on client/src/pages/HomePage.tsx
> +      ) : searchTerm ? (
J'ai modifier les ternaires par des && pour que le code soit plus lisible

2024-11-05 15:32 UTC, Ludovicscelles approved these changes

2024-11-05 15:32 UTC, brewost approved these changes

2024-11-05 16:01 UTC, jujuck approved these changes

2024-11-05 16:01 UTC, merged